### ISSUE TITLE
Feature 1 : User can view full pokedex on landing page

### ISSUE THREAD

**Issue by dennis-pnguyen** [dennis-pnguyen/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the full pokedex list from the landing page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The plan is for users to be able to have a web app where they can easily view information about their favorite pokemon. Be able to add them to a favorites list or a battle list. 
## 🖼️ Wireframes

<img width="956" alt="Screenshot 2023-08-14 at 9 55 00 AM" src="https://github.com/dennis-pnguyen/ajax-project/assets/122412863/5e48e5d6-1f45-477a-8d71-d4b274ef3e40">
<img width="945" alt="Screenshot 2023-08-14 at 9 58 14 AM" src="https://github.com/dennis-pnguyen/ajax-project/assets/122412863/3842b6c1-bc10-4a38-8c56-ed74173758aa">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create header for mobile page.
  - [x] Include icon next to heading for effect. 
- [x] Format body with red `background color` .
- [x] Include search bar with placeholder text and font to match figma included
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Add buttons for 'Favorites' and button for "battle list' using FontAwesome icons
- [x] Create layout classes for mobile and desktop functionality.
- [x] Create placeholders for pokedex entries before API integration
- [x] Add `div` elements to wrap the images and text together to form a 'card'.
  - [x] Add `GET` request for pokeAPI in order to pull data on '`name`', '`number`', '`image`' and '`flavor-text`'.
  - [x] API will pull image, pokemon number, and pokemon name and render onto home page on the placeholders
- [x] Clicking on pokemon entry will bring up individual pokemon entry for user to view information
  - [x] This page should also include the favorite and battle list buttons
  - [x] Individual pokemon flavor text should also be rendered on this view as well as `type` above the flavor text.
- [x] Add `hover` effect to card entries to let user know which one they are hovering over.
- Clean up  
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by dennis-pnguyen** [comment]
Issue 1 complete
